import random

from typing import Optional
from pydantic import BaseModel, Field
from models.Inventory import Products  # Import your actual SQLAlchemy model


#API GATEWAY VALIDATION
class ProductRequest(BaseModel):
    product_id:Optional[int] = None #auto-generated by db.
    product_name: str = Field(min_length=5, max_length=50) #mandatory
    supplier_id: Optional[int] = None
    unit_price: float = Field(gt=0)#price > 0
    unit_in_stock: int = Field(ge=0)
    unit_on_order: Optional[int] = Field(default=0,ge=0)
    reorder_level: Optional[int] = Field(default=0,ge=0)
    discontinued: Optional[int] = Field(default=0) #mandatory
    category_id: Optional[int] = None
    quantity_per_unit: Optional[str] = Field(default="",min_length=0)

    model_config = {
        "json_schema_extra":{
            "example":{
                "product_name":"SuperDry",
                "unit_price":1.0,
                "unit_in_stock":1,
            }
        }
    }




class ProductBuilder:

    def __init__(self, existing_product: Products=None):
        self.product = existing_product or Products()

    def __str__(self):
        return f"{self.product.product_name} @ {self.product.unit_price}"

    def set_name(self, name: str):
        self.product.product_name = name
        return self # Allows for method chaining

    def set_id(self,id:int):
        self.product.product_id = id
        return self

    def set_units_in_stock(self,units:int):
        self.product.unit_in_stock = units
        return self

    def set_reorder_level(self,reorder_level: int):
        self.product.reorder_level = reorder_level
        return self
    def set_category_id(self,category_id:Optional[int]):
        if category_id!=None:
            self.product.category_id = category_id
        return self


    def set_supplier(self, supplier_id: Optional[int]):
        if supplier_id!=None:
            self.product.supplier_id = supplier_id
        return self

    def set_price(self, price: float):
        self.product.unit_price = price
        return self

    def set_discontinued(self, discontinued: int):
        self.product.discontinued = discontinued
        return self

    def set_unit_on_order(self, unit_on_order: int):
        self.product.unit_on_order = unit_on_order
        return self

    def set_stock(self, stock: int):
        self.product.unit_in_stock = stock
        return self

    def set_owner_id(self, user_id: int=None):
        self.product.owner_id = user_id
        return self

    def build(self):
        # better than is None Since it checks for Empty String as well.
        if not self.product.product_name:
            raise ValueError("Product name cannot be empty")

        if self.product.unit_price < 0:
            raise ValueError("Price cannot be negative")

        if self.product.unit_in_stock!=None and self.product.unit_price < 0:
            raise ValueError("Stock cannot be negative")

        return self.product
